---
- hosts: localhost
  vars_files:
  - imglist.yml
  tasks:
  - name: Pull images from dockerhub
    docker_image:
     name: "{{item}}"
     pull: yes
     with_items:
     - "{{img}}"
    ignore_errors: true
